In [1]:
import os
path = os.path.abspath(os.path.join('..'))
print(path)
import sys

sys.path.insert(0,path)
print(sys.executable)

/home/scuervo91/dev/dcapy
/home/scuervo91/anaconda3/envs/reservoir/bin/python


In [2]:
from dcapy import dca
import numpy as np 
import pandas as pd
from datetime import date
import matplotlib.pyplot as plt
import seaborn as sns 
from scipy import stats

# dcapy Basis Examples to try

## Basics Equations

First Section will explore the Arps Declination Analysis equations. 
Starting from Equations used to calculate rate then cumulatives.

The library numpy is used to performed the majority of operations

### Exponential b = 0, Examples

The time array used with this function is relative to a Initial Time which is always 0

In [3]:
time1 = [0,2,3,4,10]
qi1 = 500
di1 = 0.3 
dca.arps_exp_rate(time1,qi1,di1)

array([500.        , 274.40581805, 203.28482987, 150.59710596,
        24.89353418])

Cumulative volume can be calculated  for any timestep

In [4]:
dca.arps_exp_cumulative(time1,qi1,di1)


array([   0.        ,  751.98060651,  989.0505671 , 1164.67631348,
       1583.68821939])

### Hyperbolic 0<b<1, Examples

The time array used with this function is relative to a Initial Time which is always 0

In [5]:
b = 0.5
dca.arps_hyp_rate(time1,qi1,di1,b)

array([500.        , 295.85798817, 237.81212842, 195.3125    ,
        80.        ])

In [6]:
dca.arps_hyp_cumulative(time1,qi1,di1,b,ti=0)

array([  -0.        ,  769.23076923, 1034.48275862, 1250.        ,
       2000.        ])

### Armonic, Examples

The time array used with this function is relative to a Initial Time which is always 0

In [7]:
b = 1
dca.arps_hyp_rate(time1,qi1,di1,b)

array([500.        , 312.5       , 263.15789474, 227.27272727,
       125.        ])

In [8]:
dca.arps_arm_cumulative(time1,qi1,di1,b,ti=0)

array([   0.        ,  783.33938208, 1069.75647695, 1314.09560061,
       2310.49060187])

## Use arps_forecast and arps_cumulative 
independently of the b. It internally uses the appropiate equation

In [9]:
print('Examples Arps Forecast function')

print('Example 1. Single Values')
time1 = [0,2,4,6]
qi1 = 500,
di1 = 0.3
b1 = 0 
f1 = dca.arps_forecast(time1,qi1,di1,b1)
print('Forecast Example 1')
print(f1)


Examples Arps Forecast function
Example 1. Single Values
Forecast Example 1
[500.         274.40581805 150.59710596  82.64944411]


In [10]:
dca.arps_cumulative(time1,qi1,di1,b1)

array([   0.        ,  751.98060651, 1164.67631348, 1391.16851963])

In [11]:
print('\nExample 2. Multiple values')
time2 = [0,2,4,6]
qi2 = [600,700,900]
di2 = 0.3
b2 = [0,0.5,1]
print(f' ->Time array {time2}\n ->qi {qi2}\n -> di {di2}\n b {b2}')    
f2 = dca.arps_forecast(time2,qi2,di2,b2)
print('Forecast Example 2')
print(f2)
f2.shape


Example 2. Multiple values
 ->Time array [0, 2, 4, 6]
 ->qi [600, 700, 900]
 -> di 0.3
 b [0, 0.5, 1]
Forecast Example 2
[[600.         700.         900.        ]
 [329.28698166 414.20118343 562.5       ]
 [180.71652715 273.4375     409.09090909]
 [ 99.17933293 193.90581717 321.42857143]]


(4, 3)

In [12]:
dca.arps_cumulative(time2,qi2,di2,b2)

array([[   0.        ,   -0.        ,    0.        ],
       [ 902.37672781, 1076.92307692, 1410.01088774],
       [1397.61157618, 1750.        , 2365.37208109],
       [1669.40222356, 2210.52631579, 3088.85825154]])

# Arps Class

In [13]:
print('Example Arps Class')
#print(dca.time_converter_matrix)
qi = 5000
di = 0.3
b = 0
ti = 0
di_f = 'A'
print(f' ->qi {qi}\n -> di {di}\n b {b}\n ->di_freq {di_f}')  
dc = dca.Arps(qi,di,b,ti,freq_di=di_f)

Example Arps Class
 ->qi 5000
 -> di 0.3
 b 0
 ->di_freq A


In [14]:
dc

Declination 
 Ti: 0 
 Qi: 5000 bbl/d 
 Rate: 0.3 A 
 b: 0

In [15]:
print('Calculate Daily Basis each day')
#print(dc.forecast(start=0,end=1000,freq_input='D',freq_output='D'))
dd = dc.forecast(start=0,end=365,freq_input='D',freq_output='D')

dd

Calculate Daily Basis each day


rate    cumulative
0    5000.000000  0.000000e+00
1    4995.892099  4.997946e+03
2    4991.787574  9.991785e+03
3    4987.686420  1.498152e+04
4    4983.588636  1.996716e+04
..           ...           ...
360  3719.344717  1.558131e+06
361  3716.288977  1.561848e+06
362  3713.235748  1.565563e+06
363  3710.185028  1.569275e+06
364  3707.136813  1.572984e+06

[365 rows x 2 columns]

In [16]:
print('Calculate Daily Basis each Month')
print(dc.forecast(start=0,end=365,freq_input='D',freq_output='M'))

Calculate Daily Basis each Month
            rate    cumulative
0    5000.000000  0.000000e+00
30   4878.219897  1.481658e+05
60   4759.405873  2.927229e+05
90   4643.485686  4.337591e+05
120  4530.388854  5.713602e+05
150  4420.046610  7.056100e+05
180  4312.391864  8.365899e+05
210  4207.359159  9.643797e+05
240  4104.884633  1.089057e+06
270  4004.905979  1.210698e+06
300  3907.362406  1.329376e+06
330  3812.194607  1.445163e+06
360  3719.344717  1.558131e+06


In [17]:
print('Calculate Daily Basis each Year')
print(dc.forecast(start=0,end=366,freq_input='D',freq_output='A'))

Calculate Daily Basis each Year
            rate    cumulative
0    5000.000000  0.000000e+00
365  3704.091103  1.576689e+06


In [19]:
print('Calculate Monthly Basis each Month')
print(dc.forecast(start=0,end=13,freq_input='M',freq_output='M'))

Calculate Monthly Basis each Month
           rate    cumulative
0   5000.000000  0.000000e+00
1   4876.549560  1.481405e+05
2   4756.147123  2.926235e+05
3   4638.717432  4.335391e+05
4   4524.187090  5.709755e+05
5   4412.484513  7.050186e+05
6   4303.539882  8.357521e+05
7   4197.285104  9.632579e+05
8   4093.653765  1.087615e+06
9   3992.581094  1.208903e+06
10  3894.003915  1.327195e+06
11  3797.860616  1.442567e+06
12  3704.091103  1.555091e+06


In [20]:
print('Calculate Monthly Basis each Year')
print(dc.forecast(start=0,end=13,freq_input='M',freq_output='A'))

Calculate Monthly Basis each Year
           rate    cumulative
0   5000.000000  0.000000e+00
12  3704.091103  1.555091e+06


In [23]:
print('Calculate Year Basis each Year')
print(dc.forecast(start=0,end=2,freq_input='A',freq_output='A'))

Calculate Year Basis each Year
          rate    cumulative
0  5000.000000  0.000000e+00
1  3704.091103  1.576689e+06


In [24]:
print('Calculate Year Basis each Year - Rate Limit')
print(dc.forecast(start=0,end=15,freq_input='A',freq_output='A',rate_limit=500))


Calculate Year Basis each Year - Rate Limit
          rate    cumulative
0  5000.000000  0.000000e+00
1  3704.091103  1.576689e+06
2  2744.058180  2.744729e+06
3  2032.848299  3.610035e+06
4  1505.971060  4.251069e+06
5  1115.650801  4.725958e+06
6   826.494441  5.077765e+06
7   612.282141  5.338390e+06


## Using Arps with dates

In [25]:
print('Example Arps Class')
#print(dca.time_converter_matrix)
qi = 5000
di = 0.3
b = 0
ti = date(2021,1,1)
di_f = 'A'
dc1 = dca.Arps(qi,di,b,ti,freq_di=di_f)
print(dc1)

Example Arps Class
Declination 
 Ti: 2021-01-01 
 Qi: 5000 bbl/d 
 Rate: 0.3 A 
 b: 0


In [27]:
from_time = date(2021,1,1)
to_time = date(2023,1,1)

dc1.forecast(start=from_time,end=to_time)

rate    cumulative
0    5000.000000  0.000000e+00
1    4995.892099  4.997946e+03
2    4991.787574  9.991785e+03
3    4987.686420  1.498152e+04
4    4983.588636  1.996716e+04
..           ...           ...
726  2753.094588  2.733735e+06
727  2750.832700  2.736487e+06
728  2748.572671  2.739237e+06
729  2746.314498  2.741984e+06
730  2744.058180  2.744729e+06

[731 rows x 2 columns]

In [28]:
dc1.forecast(start=from_time,end=to_time,freq_input='M')

rate    cumulative
30   4878.219897  1.481658e+05
58   4767.235988  2.831962e+05
89   4647.303819  4.291137e+05
119  4534.113992  5.668280e+05
150  4420.046610  7.056100e+05
180  4312.391864  8.365899e+05
211  4203.902476  9.685853e+05
242  4098.142420  1.097260e+06
272  3998.327979  1.218701e+06
303  3897.739683  1.341083e+06
333  3802.806255  1.456586e+06
364  3707.136813  1.572984e+06
395  3613.874184  1.686453e+06
423  3531.655282  1.786486e+06
454  3442.807346  1.894584e+06
484  3358.954260  1.996606e+06
515  3274.451065  2.099418e+06
545  3194.698467  2.196450e+06
576  3114.327552  2.294235e+06
607  3035.978576  2.389559e+06
637  2962.034219  2.479525e+06
668  2887.516576  2.570188e+06
698  2817.188163  2.655754e+06
729  2746.314498  2.741984e+06

In [29]:
dc1.forecast(start=from_time,end=to_time,freq_input='A')

rate    cumulative
364  3707.136813  1.572984e+06
729  2746.314498  2.741984e+06

In [30]:
dca.time_converter_matrix

to        A         D          M
from                            
A       1.0  0.002740   0.083333
D     365.0  1.000000  30.000000
M      12.0  0.033333   1.000000